# Generated by Django 3.0.8 on 2020-07-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiempl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
