# Generated by Django 3.0.8 on 2020-07-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiempl', '0006_auto_20200712_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
