# Generated by Django 3.0.8 on 2020-07-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiempl', '0013_auto_20200714_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='modified',
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apiempl.UserForumPost'),
        ),
    ]
